### ISSUE TITLE
Fix link in atmosphere package

### ISSUE THREAD

**Issue by talha-asad** [schiller/meteor-twit#1]
The link for the github repo and for issues are both pointing to a repo name "twit" when its "meteor-twit". I know you kind of did this in a rush ;)

**Comment by schiller** [comment]
Thanks for pointing out! :)

**Comment by cutemachine** [comment]
Thanks for the package. Link from Atmosphere back to GitHub is still broken :)

**Comment by talha-asad** [comment]
Yeah i think the repo was renamed to `meteor-twit`

**Comment by talha-asad** [comment]
Fixed this and updated the npm package version. Please merge my PR.

**Comment by schiller** [comment]
Thanks!

**Comment by talha-asad** [comment]
Please publish the new package on atmosphere as well, otherwise no gain :stuck_out_tongue:

**Comment by schiller** [comment]
Done!
