### ISSUE TITLE
Package no longer necessary

### ISSUE THREAD

**Issue by dandv** [schiller/meteor-twit#4]
Starting with Meteor 1.3, wrapper packages are no longer necessary. I've been able to use Twit on the server directly by installing from npm. An important note is that in stream `on` handlers, you must use `Meteor.bindEnvironment`. However, this package doesn't take care of that.

If the package is no longer necessary, it would be great to [archive this repo](https://help.github.com/articles/archiving-a-github-repository/) so that it readily appears as no longer maintained in GitHub searches, and to deprecate the package on Atmoshpere.

    meteor admin set-unmigrated <package:name>

**Comment by schiller** [comment]
Package deprecated on atmosphere and repo archived.
